[package]
name = "aethon"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0"
serde_json = "1.0"
iced = { version = "0.10", features = ["tokio"] }
tokio = "1.33"
rfd = "0.12"
sysinfo = "0.29"
